repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: check-yaml
    -   id: check-json
    -   id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
  - repo: https://github.com/ambv/black
    rev: 24.4.2
    hooks:
      - id: black
        language: python
        args:
          - -t
          - py36
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args:
          - --profile
          - black
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.4.5
    hooks:
      # Run the linter.
      - id: ruff